title: blinkbox Books tech blog
email: jobs@blinkbox.com
description: Thoughts from the engineering team at blinkbox Books.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blinkboxbooks.github.io"
github_username:  blinkboxbooks

analytics:
  google: 'UA-43984684-7'

# Build settings
markdown: kramdown

authors:
  jphastings:
    name: JP Hastings-Spital
    display_name: JP
    gravatar: 8f196eedfa0d23f02e6d92159e84e63d
    github: jphastings
    bio: "writes code for ingesting publisher books and metadata. When he's not doing that he's mostly swing dancing but no, it turns out you really can't do both of those at the same time."
  gregbeech:
    name: Greg Beech
    display_name: Greg
    gravatar: 8e731d0b83306e18d2221350cb720338
    github: gregbeech
    bio: "heads up the platform team, thinks a lot about processes, web services and messaging, and occasionally writes code. In his spare time he's probaby either riding motorbikes or buying more of them."
  aikhelis:
    name: Aliaksandr (Alex) Ikhelis
    display_name: Alex
    gravatar: 7df7e873a2bd6a5b93daaffe3a6e133c
    github: aikhelis
    bio: "leads the team of QA engineers and SDETs, trying his hard in managing the testing process and contributing to the test codebases at the same time. Combining incompatible never works; thus he can be often seen recovering his temper by playing the guitar or reading a book."
